# Generated by Django 4.1.2 on 2022-10-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='pets_allowd',
            new_name='pets_allowed',
        ),
    ]
